// 加密前端数据，注意这不是一对密钥，对应的公钥和私钥在后端
export const RSA_PRIV_KEY = `
-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANFsMMbmM2PGXnMXiidJyFIDjKN3z4oJ
whBM2/HQQDplntg1J54+BLBhkhd4jwy0kdxwOpaWMI6uvrWqsz5J7OECAwEAAQ==
-----END PUBLIC KEY-----
`;

// 解密后端数据
export const RSA_PUB_KEY = `
-----BEGIN PRIVATE KEY-----
MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEAtKTjtxKM9jSqRYCD
omLkk4VXGft1jADrQn9VTA4pWtL92X6dvWugF3SAsq/GP6v3LoMHfzUNWaeHRvJ4
xL0j0QIDAQABAkAy2uDIn05T2cu9uUpVouWaqkU1KVeUTIXuuI441RvLV3UaplpY
HQ4fgusL78kYFra8uKeeg+2Df87F7PYj378JAiEA74Ex/0O6pmIGlxqek+HYfg41
yIO6hVWhMQcCflskCGcCIQDBFeZCwL3K/xfLXJX/R31Lu+Fm9G+uLkxnUfOHg1ov
BwIgAuImTPFuzNP/SlBqulMMvS/Em/5h/3rxbtqrwAOu4l8CIFo7xL7fWhLawaDs
5MBHBXv2EnFNvD9XLad/OeLTdLrTAiA6Hjehc8hlQSNvn8l7r7QBdcS9RpiTTaPl
cgpHfBgrWg==
-----END PRIVATE KEY-----
`;
