@startuml
    left to right direction
    :学生: as student
    :管理员: as admin
    :游客: as visitor
    :教师: as teacher
    :管理员: as adminAccount
    :普通用户: as commonAccount
    :游客账户: as visitorAccount

    rectangle 基于WebGL的AR交互系统{
        (首页推送) as home
        (AR 预览) as preview
        (AR 识别) as identify
        (我的信息) as my
        (上传) as update

            home ..> (按需推送):<<include>>
            home ..> (模型查找):<<include>>
            home ..> (模型显示):<<include>>
            home ..> (模型信息):<<include>>

            (模型信息) <.. (简略信息):<<include>>
            (模型信息) <.. (详细信息):<<include>>

            preview ..> (模型调整):<<include>>

            (模型调整) <.. (交互调整):<<extend>>
            (模型调整) <.. (数值调整):<<extend>>

            identify ..> (交互模型):<<include>>
            identify ..> (场景信息):<<include>>

            my ..> (信息查询):<<include>>
            my ..> (用户设置):<<include>>

          update ..> (上传模型):<<include>>

    }

    student --|> commonAccount:"登录"
    teacher --|> commonAccount:"登录"
    admin --|> adminAccount:"登录"
    visitor --|> visitorAccount:"跳过登录"

    adminAccount -- home
    adminAccount -- preview
    adminAccount -- identify
    adminAccount -- update
    adminAccount -- my

    commonAccount -- home
    commonAccount -- my
    commonAccount -- preview
    commonAccount -- identify

    visitorAccount -- home
    visitorAccount -- preview
    visitorAccount -- identify
@enduml